[package]
name = "graph"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { version = "0.6.0", features = ["html_reports"] }
rand = "0.9.1"
rayon = "1.10.0"


[[bench]]
name = "sink_bench"
harness = false

[[bench]]
name = "square_matrix_bench"
harness = false

